version: '3.9'

services:

  matching-service:
    container_name: "matching-service"
    build: 
      context: ./matching-service
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
      - user-service
      - collaboration-service
    restart: on-failure
    environment:
      - MODE=DEV
      - FRONTEND_URI=http://localhost:3000
      - COLLABORATION_SERVICE_URI=http://collaboration-service:8003
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - PORT=8001

  user-service:
    container_name: "user-service"
    build: 
      context: ./user-service
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - ENV=DEV
      - DB_LOCAL_URI=mongodb://mongodb:27017/user-service
      - DB_CLOUD_URI=mongodb+srv:// {rest-of-cloud-URL}
      - PW_SALT=$$2b$$10$$zzlQzTUZKmvPuIejOTr0Ke
      - JWT_SECRET_KEY=Swe4g7c?UBm5Nrd96vhsVDtkyJFbqKMTm!TMw5BDRLtaCFAXNvbq?s4rGKQSZnUP 
      - DB_LOCAL_JSON_PATH=/usr/user-service/src/dev-data.json

  frontend:
    container_name: "frontend"
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - ywebrtc
    environment:
      - PORT=3000
      - MATCHING_SERVICE_URI=http://matching-service:8001
      - USER_SERVICE_DOMAIN=http://user-service:8000
      - COLLABORATION_SERVICE_DOMAIN=http://collaboration-service:8003
      - COLLABORATION_SERVICE_SOCKET_DOMAIN=ws://collaboration-service:8003
      - Y_JS_SIGNALLING_SERVER=ws://ywebrtc:4444

  ywebrtc:
    container_name: "ywebrtc"
    ports:
      - "4444:4444"
    build: 
      context: ./frontend/ywebrtc

  question-service:
    container_name: question-service
    build: 
      context: ./question-service
    ports:
      - '8002:8002'
    depends_on:
      - mongodb
    environment:
      - ENV=DEV
      - DB_LOCAL_URI=mongodb://mongodb:27017/question-service
      - PORT=8002

  mongodb:
    container_name: "mongodb"
    image: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq
    ports:
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
      
  collaboration-service:
    container_name:  "collaboration-service"
    build: 
      context: ./collaboration-service
    ports:
      - "8003:8003"
    depends_on:
      - mongodb
    environment:
      - ENV=DEV
      - HOST=0.0.0.0
      - PORT=8003
      - MONGODB_CLOUD_URI=
      - MONGODB_LOCAL_URI=mongodb://mongodb:27017/
      - QUESTION_SERVICE_HOST=http://question-service:8002
      - USER_SERVICE_HOST=http://user-service:8000
      - FRONTEND_HOST=http://localhost:3000
      - MATCHING_SERVICE_HOST=http://matching-service:8001
      - DAILY_VIDEO_TOKEN=a4648e74d5bc82c51a31925d61ec9a015c7b6c83ce56140754622bf9d285d79d

