version: '3.9'

services:
  
  user_service:
    container_name: "user-service"
    build: 
      context: .
    volumes:
      - .:/usr/userService
      - /usr/userService/node_modules
    ports:
      - "8000:8000"
  
  mongodb:
    container_name: "mongodb"
    image: mongo
    ports:
      - "27017:27017"