version: '3'
services:
  app:
    container_name: question-service-app
    restart: always
    build: .
    ports:
      - '8002:8002'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'