---
    name: Node.js CI subfolder
    
    on:
      push
    
    jobs:
      build:
    
        runs-on: ubuntu-latest
        defaults:
          run:
          working-directory: ./user-service
        strategy:
          matrix:
            node-version: [12.x, 14.x, 16.x]
    
        steps:
          - uses: actions/checkout@v3
    
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v3
            working-directory: ./user-service
            with:
              node-version: ${{ matrix.node-version }}
              cache: 'npm'
          - run: npm ci
          - run: npm run build --if-present
          - run: npm run test-ci
    